version: '2'
services:
    ejemplojhipsteronline-app:
        image: ejemplojhipsteronline
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ejemplojhipsteronline-mysql:3306/ejemplojhipsteronline?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ejemplojhipsteronline-mysql:
        extends:
            file: mysql.yml
            service: ejemplojhipsteronline-mysql
